version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        networks:
            - networktp6
        volumes:
            - type: bind
              source: ./text_file.txt
              target: /app/text_file.txt
        depends_on:
            - db
    db:
        container_name: mongodb
        image: mongo:latest
        networks:
           - networktp6
networks:
   networktp6:
       driver: bridge
volumes:
    mongodb_data:
        external: true
